{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<form method="post" action={"/notification/settings/"|ezurl}>

    <section class="hgroup">
      <h1>{"Impostazioni delle notifiche"|i18n('openpa_sensor/settings')}</h1>
    </section>

    {let handlers=fetch('notification','handler_list')}

        <p>
            {section name=Handlers loop=$handlers}
            {if array( 'ezsubtree', 'ezcollaboration' )|contains( $Handlers:item.id_string )}
                {include handler=$Handlers:item uri=concat( "design:notification/handler/",$Handlers:item.id_string,"/settings/edit.tpl")}
            {/if}
            {/section}
        </p>

    {/let}

    {*<div>
        <input class="button btn btn-success" type="submit" name="Store" value="{'Salva le impostazioni'|i18n('openpa_sensor/settings')}" />
    </div>*}
    
</form>
