{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default page_uri_suffix=false() left_max=3 right_max=3}
{default name=ViewParameter page_uri_suffix=false() left_max=$left_max right_max=$right_max}

{let page_count=int( ceil( div( $item_count,$item_limit ) ) )
     current_page=min($:page_count, int( ceil( div( first_set( $view_parameters.offset, 0), $item_limit ) ) ) )
     item_previous=sub( mul( $:current_page, $item_limit ), $item_limit ) item_next=sum( mul( $:current_page, $item_limit ), $item_limit )
     left_length=min($ViewParameter:current_page,$:left_max)
     right_length=max(min(sub($ViewParameter:page_count,$ViewParameter:current_page,1),$:right_max),0)
     view_parameter_text=""
     offset_text=eq( ezini( 'ControlSettings', 'AllowUserVariables', 'template.ini' ), 'true' )|choose( '/offset/', '/(offset)/' )}
    {* Create view parameter text with the exception of offset *}

{section loop=$view_parameters}
    {section-exclude match=$:key|eq('offset')}
    {section-exclude match=$:item|eq('')}
    {set view_parameter_text=concat($:view_parameter_text,'/(',$:key,')/',$:item)}
{/section}


{section show=$:page_count|gt(1)}

    <div class="pagination-container text-center replies-navigator">
        <ul class="pagination">
            {switch match=$:item_next|lt($item_count)}
            {case match=1}
                <li><a href={concat($page_uri,$:offset_text,$:item_next,$:view_parameter_text,$page_uri_suffix)|ezurl}><span class="text">{"Visualizza commenti precedenti"|i18n("dimmi/navigator")}</span></a></li>
            {/case}
            {case}
            {/case}
            {/switch}
        </ul>
    </div>
{/section}

{/let}
{/default}
{/default}

